
---

- name: include common variables
  include_vars: ../defaults.yml

- name: copy local files to remote
  copy: src=~/.git dest=~/.git mode=0644 remote_src=no
- name: fetch server code
  git: repo=git@github.com:ossiemarks/barclays-jenkins-jobs.git dest=~/jenkins-jobs accept_hostkey=yes version=master
- name: pull drupal
  git: repo=git://github.com/reload/jenkins-drupal-template.git dest=~/template accept_hostkey=yes version=master
- name: pull
  git: repo=git@github.com:ricardoamaro/docker-drupal.git dest=~/drupal accept_hostkey=yes version=master
- name: start jenkins
  command: docker run -d pp2l/jenkins
- name: start containers
  command: docker build -t {{ app_name }}/drupal ~/drupal
- name: start jenkins-jobs builder
  command: docker run --dns={{ dns }} -e JENKINS_URL=http://{{ host }} -v "$(pwd)":/opt/src -it pp2l/jenkins-configure
- name: copy tempate
  shell: mv ~/template ~/jenkins-jobs/jobs/
